---
- name: Converge
  hosts: all
  gather_facts: true
  tasks:
    - name: "Include usegalaxy_eu.grafana_matrix_forwarder"
      ansible.builtin.include_role:
        name: "usegalaxy_eu.grafana_matrix_forwarder"
      vars:
        matrix_forwarder_systemd_user: root
        matrix_forwarder_systemd_group: root
        # matrix_forwarder_version: "v0.8.2"  # (compiles on the root of the archive)
        matrix_forwarder_version: "0.6.0"  # (compiles on the "src" subdirectory)
