---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: rocky8
    image: docker.io/geerlingguy/docker-rockylinux8-ansible:latest
    pre_build_image: true
    privileged: true
    tmpfs:
      - /run
      - /tmp
    command: /sbin/init
    volume_mounts:
    - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
  - name: rocky9
    image: docker.io/geerlingguy/docker-rockylinux9-ansible:latest
    pre_build_image: true
    privileged: true
    volume_mounts:
    - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    tmpfs:
      - /run
      - /tmp
    command: /sbin/init
provisioner:
  name: ansible
verifier:
  name: ansible
