---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: rocky8
    image: docker.io/geerlingguy/docker-rockylinux8-ansible:latest
    pre_build_image: true
    privileged: true
    systemd: always
    command: /sbin/init
  - name: rocky9
    image: docker.io/geerlingguy/docker-rockylinux9-ansible:latest
    pre_build_image: true
    privileged: true
    systemd: always
    command: /sbin/init
provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
      callback_whitelist: profile_tasks, timer, yaml
    ssh_connection:
      pipelining: false  
verifier:
  name: ansible
