---
name: CI
"on":
  pull_request:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: "usegalaxy_eu.flower"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: Run yaml-lint
        uses: ibiqlik/action-yamllint@v3

      - name: Run ansible-lint
        uses: ansible/ansible-lint@v24
